version: "3.9"
services:
    colorbrains-api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        env_file:
            - ./.env
    postgres:
        container_name: postgres
        restart: unless-stopped
        image: postgres:latest
        volumes:
            - ./colorbrains_api/sql/:/docker-entrypoint-initdb.d/
            # - ./postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - ./.env
