version: "3.9"
services:
    colorbrains-api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
        - ./colorbrains_api:/app/colorbrains_api/
        environment:
            COLORBRAINS_CONN_STRING: ${COLORBRAINS_CONN_STRING:-postgresql://colorbrains:colorbrains@host.docker.internal:5450/colorbrains}
            X_API_KEY: ${COLORBRAINS_X_API_KEY:-xyz}


# https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach