version: "3.9"
services:
    colorbrains-api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        environment:
            - POSTGRES_USER=colorbrains
            - POSTGRES_PASSWORD=colorbrains
            - POSTGRES_DB=colorbrains
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=localhost
    
    postgres:
        container_name: postgres
        restart: unless-stopped
        image: postgres:latest
        volumes:
            - ./colorbrains_api/sql/:/docker-entrypoint-initdb.d/
            # - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=colorbrains
            - POSTGRES_PASSWORD=colorbrains
            - POSTGRES_DB=colorbrains
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=localhost
        ports:
            - 5432:5432
